### ISSUE TITLE
Incorrect number of screenshots

### ISSUE THREAD

**Issue by PunchDrunkL0ve** [Audionut/Upload-Assistant#111] opened 2024-10-28 14:50 UTC
Hi,

Not sure if this issue is related to the recent commit https://github.com/Audionut/Upload-Assistant/commit/ff147ff3653a74e4e7e24e269da643cea9945dbe but now the script only puts two screenshots in the [PTP] description (for a film) which causes the upload to fail. TV mini-series uploads are successful.

Thanks.

**Comment by Audionut** [comment] 2024-10-28 21:17
Yes sorry. I'd doing an overhaul of that functionality now, in the meantime, add the config option https://github.com/Audionut/Upload-Assistant/commit/ccd695b07f9b555bbcbd12ac569336c70a8dc278#diff-79121935774362ae6d2fd9619f64fcdaea2104da659a1eeeb240b636b9222ad8R30 set to 3 as a workaround.

**Comment by PunchDrunkL0ve** [comment] 2024-10-29 08:07
No probs and many thanks for providing a workaround so quickly. I assume you suggest using "multiScreens": "3"

**Comment by Audionut** [comment] 2024-10-29 08:43
That's correct.

Or you could revert to this PTP file https://github.com/Audionut/Upload-Assistant/blob/c27b44a0ae638aaca51ca662d58046edd45dff41/src/trackers/PTP.py

And change https://github.com/Audionut/Upload-Assistant/blob/c27b44a0ae638aaca51ca662d58046edd45dff41/src/trackers/PTP.py#L688

too
`s = multiprocessing.Process(target=prep.screenshots, args=(file, f"FILE_{i}", meta['uuid'], meta['base_dir'], meta, 3, True))`

Where the 2 is changed to a 3. This would have the exact functionality of the original, whilst correcting only 1 image when multiple files.

Up to you if you're comfortable modifying files. I hope to have this properly fixed within 24 hours.

**Comment by Audionut** [comment] 2024-10-29 13:32
I got around to looking at PTP to integrate it with some other changes I made, and the existing code looks and works fine here.

Here https://github.com/Audionut/Upload-Assistant/blob/02ce1f317da62eec5bf921e46984b71cb2552ff8/src/trackers/PTP.py#L635

Is where it's handling a single disc, and being instructed to use the existing image list, the original uploaded images.
``` python
        # Number of screenshots to capture
        "screens": "6",
```

And here is the same instruction for a single file 
https://github.com/Audionut/Upload-Assistant/blob/02ce1f317da62eec5bf921e46984b71cb2552ff8/src/trackers/PTP.py#L714

Not sure where you are at, if you can test an update of the master branch.

**Comment by Audionut** [comment] 2024-10-29 16:11
Did you actually have `C:\Users\me\Downloads\Upload-Assistant\tmp\FILE_3-2.png` ?

**Comment by PunchDrunkL0ve** [comment] 2024-10-29 16:19
I see a FILE_3-0.png and a FILE_3-1.png but no FILE_3-2.png

Did the script create a FILE_3-2.png? not sure.

**Comment by PunchDrunkL0ve** [comment] 2024-10-29 16:25
Also, doesn't seem to use the MEDIAINFO_CLEANPATH and keeps the original complete name in the [PTP] Description.

**Comment by Audionut** [comment] 2024-10-29 16:35
You can compare the code since before I touched it https://github.com/Audionut/Upload-Assistant/blob/61415b7ed7d0442f3475dae6fb9b828d0958182a/src/trackers/PTP.py

It has always sent the full path. I'm pretty sure PTP parses those paths locally on upload. In any event, I already have clean paths in the updated code I am working on.

Did you try a clean meta state? Delete everything from the tmp directory and start again. It smells like you have a mismatch between what the meta is reporting you have as files, and what files are actually on disc. 

I've confirmed a few use cases for PTP here without issue, and confirmed I'm not locally running PTP code that doesn't match the current master branch.

**Comment by Audionut** [comment] 2024-10-29 16:38
BTW: if you keep having issues, you can reach me here https://discord.gg/9zFyXZpR which will probably be quicker.

**Comment by Audionut** [comment] 2024-10-30 04:39
Do you want to try the descriptions branch https://github.com/Audionut/Upload-Assistant/pull/112

It all seems to work fine here, and now works at UNIT3D sites also, with the meta for new images saved. For instance, you could have PTP as your first upload tracker, have all of the needed images for the other discs/episodes created and uploaded, and all of those upload links are retained for any other site you wish to upload the pack too.

**Comment by PunchDrunkL0ve** [comment] 2024-10-30 07:10
Hi,

Yes, happy to try and provide feedback :) What's the best way to pull it?

Did a `git branch -a` but doesn't come up?
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/aither_language
  remotes/origin/image_uploading
  remotes/origin/master

**Comment by Audionut** [comment] 2024-10-30 07:30
`git fetch origin`
`git checkout -b descriptions origin/descriptions`
Should work. 

For git I use their desktop app, if for no other reason than to take a break from a command line.

**Comment by Audionut** [comment] 2024-10-30 23:03
> Is there any particular area that needs more testing?

The only major thing I guess is the flags. If you use it, particularly in production, can you run an eye over the site mediainfo box and one of the files in the description. Both subtitle flag lists should match. I've tested a whole host here, but lost track of which I've checked and which I haven't.

> 1. screenshot thumbnail size is 300 while set to 350 in config.py

I'm mindful to not start spamming sites with huge descriptions, but I think I'm just being overzealous here in the level of control exerted. I'll fix this.

> 2\. there is a bbcode error in the description for "Other files" the [center] is missing or misspelled so it appears as: Other files [/center]

I've looked through the code a couple times and cannot see where the issue is. The test pack I have been using has been fine also. I've also checked all UNIT3D sites I have access too just in case. Can you mention which pack you see the issue with?

BTW: If not noticed, there were some additional config settings added https://github.com/Audionut/Upload-Assistant/pull/112/files#diff-79121935774362ae6d2fd9619f64fcdaea2104da659a1eeeb240b636b9222ad8

And I left the PTP mediainfo alone, with the full file paths, to make sure I didn't unintentionally create issue. See `forums.php?page=1&action=viewthread&threadid=17690`

**Comment by Audionut** [comment] 2024-10-30 23:25
https://github.com/Audionut/Upload-Assistant/commit/e82094295723b87a4c3662bd6dc343134e6e683f

**Comment by PunchDrunkL0ve** [comment] 2024-10-31 06:08
> > 2. there is a bbcode error in the description for "Other files" the [center] is missing or misspelled so it appears as: Other files [/center]
> 
> I've looked through the code a couple times and cannot see where the issue is. The test pack I have been using has been fine also. I've also checked all UNIT3D sites I have access too just in case. Can you mention which pack you see the issue with?
> 

[src/trackers/COMMON.py](https://github.com/Audionut/Upload-Assistant/pull/112/files#diff-5dd2a381e67c596cd650a94aebc8845cc6cb2d76df5a1f77fa5c365b138fa065)

Maybe line 211-212 ?

**Comment by Audionut** [comment] 2024-10-31 06:20
I didn't consider that use case. Got it.

Damn, the loop is slow when only showing the first file, and in that specific instance, it makes better sense to keep all of the original images also.

**Comment by Audionut** [comment] 2024-11-02 07:24
Thanks for your testing and feedback.

**Closed** 2024-11-02 07:23 UTC
